# Generated by Django 3.0 on 2020-03-23 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recordrecei', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField(blank=True, null=True)),
                ('rfid_item', models.CharField(blank=True, max_length=40, null=True)),
                ('roomName', models.CharField(max_length=120)),
                ('rfid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recordrecei.docitem_rfid')),
            ],
        ),
        migrations.CreateModel(
            name='respinv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_resp', models.CharField(max_length=120)),
                ('date_resp', models.DateField(blank=True, null=True)),
                ('date_back', models.DateField(null=True)),
                ('resp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='responsible.rooms')),
            ],
        ),
    ]
