# Generated by Django 3.0 on 2020-03-23 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordrecei', '0001_initial'),
        ('responsible', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='rfid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recordrecei.docitem_rfid'),
        ),
    ]
