# Generated by Django 3.0 on 2020-03-23 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doc_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(max_length=300)),
                ('price', models.FloatField()),
                ('is_stay', models.CharField(default="It's Stay", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_it', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('item_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='docitem_rfid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid', models.CharField(max_length=50, null=True, unique=True)),
                ('doc_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recordrecei.doc_items')),
            ],
        ),
        migrations.AddField(
            model_name='doc_items',
            name='ID_doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recordrecei.documents'),
        ),
        migrations.AddField(
            model_name='doc_items',
            name='id_items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recordrecei.items'),
        ),
    ]
